### ISSUE TITLE
KeyError: 'model'

### ISSUE THREAD

**Issue by fengjingchehu** [MCG-NJU/VideoMAE#119]
VideoMAE-main$ bash vis.sh
Namespace(decoder_depth=4, device='cuda:0', drop_path=0.0, imagenet_default_mean_and_std=True, img_path='./input/test1.mp4', input_size=224, mask_ratio=0.9, mask_type='tube', model='pretrain_videomae_base_patch16_224', model_path='./ckp/ucf101.pth', num_frames=16, sampling_rate=4, save_path='.demo')

Creating model: pretrain_videomae_base_patch16_224
Patch size = (16, 16)
Traceback (most recent call last):
  File "run_videomae_vis.py", line 185, in <module>
    main(opts)
  File "run_videomae_vis.py", line 102, in main
    model.load_state_dict(checkpoint['model'])
KeyError: 'model'

i wonder how can i solve this question ?

**Comment by fusu80** [comment]
你好，请问你解决这个问题了吗，我今天在运行.sh的时候也发生了这样的错误。期待你的回复。  
Hello, did you fix this problem, I also got this error when I was running the .sh today. Looking forward to hearing from you.

**Comment by censhallwe** [comment]
你是从MODEL_ZOO上下载的权重吗？那里存的时候key用的是'module'，你可以试着把key改一下
