### ISSUE TITLE
TypeError: VisionTransformer.__init__() got an unexpected keyword argument 'pretrained_cfg'

### ISSUE THREAD

**Issue by FVT34U** [MCG-NJU/VideoMAE#126]
I have this problem with running code:

Traceback (most recent call last):
  File "path\to\VideoMAEv2\run_class_finetuning.py", line 926, in <module>
    main(opts, ds_init)
  File "path\to\VideoMAEv2\run_class_finetuning.py", line 514, in main
    model = create_model(
  File "path\to\anaconda3\envs\videomae\lib\site-packages\timm\models\_factory.py", line 117, in create_model
    model = create_fn(
  File "path\to\VideoMAEv2\models\modeling_finetune.py", line 459, in vit_small_patch16_224    model = VisionTransformer(
TypeError: VisionTransformer.__init__() got an unexpected keyword argument 'pretrained_cfg'

**Comment by liuyifan6613** [comment]
pip install timm==0.4.12
