### ISSUE TITLE
finetune error

### ISSUE THREAD

**Issue by zhudongwork** [MCG-NJU/VideoMAE#60]
When I run the run_class_finetuning.py, miss this error:

Traceback (most recent call last):
  File "run_class_finetuning.py", line 558, in <module>
    main(opts, ds_init)
  File "run_class_finetuning.py", line 498, in main
    num_training_steps_per_epoch=num_training_steps_per_epoch, update_freq=args.update_freq,
  File "/content/gdrive/MyDrive/VideoMAE/engine_for_finetuning.py", line 58, in train_one_epoch
    targets = targets.to(device, non_blocking=True)
AttributeError: 'list' object has no attribute 'to'

**Comment by andyfriedrich-amd** [comment]
What was the fix for this error?
